server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://carrot-market.cpyf1l3oqcit.ap-northeast-2.rds.amazonaws.com/carrot_market?autoReconnect=true # 변경해주세요
    username: tionake # 변경해주세요
    password: '#Zndznd9687' # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전